### PR TITLE
beta development over

### PR DESCRIPTION
**Pull request by imhta**

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @imhtapm @saintaze, 
Good job. Here is the checklist for your project.
- To consider the project 'complete' it must satisfy the following points:
## General
- [x] The project has a descriptive README.md

## Navigation bar
-  [x] The Navbar should have a fixed position
-  [x]  Floats or flex display for positioning items inside the navbar

## Main Content
-  [x] The main content of the website should be wrapped with an HTML tag `<main>`

## Bottom
-  [x] It should have a 'Read comments' button and social media icons (fontawsome is recommended for the icons)

After fixing the unchecked issue please send another request to re-review this project.

Thanks 🙏

**Comment by saintaze** [comment]
Hey,

can you tell me where are these project requirements mentioned? I didn't see these requirements anywhere otherwise I would do that from the start. Just to be sure so that I start my next projects in a proper way.

**Comment by imhta** [comment]
Everything fixed. 'Read comments' button, social media icons and flex display for positioning items inside the navbar are already done as required.

**Comment by maelfosso** [comment]
Hello

# Good Job

You can submit a project completion form.

**Pull request merged**
